export const largeOffice = [
  "Attic",
  "BreakRoom",
  "Classroom",
  "ClosedOffice",
  "Conference",
  "Corridor",
  "Dining",
  "Elec/MechRoom",
  "Elevator Lobby",
  "Elevator Machine Room",
  "Elevator Shaft",
  "IT_Room",
  "Lobby",
  "Main Electrical",
  "Main Mechanical",
  "OfficeLarge Data Center",
  "OfficeLarge Main Data Center",
  "OpenOffice",
  "PrintRoom",
  "Restroom",
  "Stair",
  "Storage",
  "Vending",
];
