export const rooms = [
  // "Midway",
  // "Midway",
  "(L) Conference - 2nd Floor",
  // "(L) Conference - 3rd Floor",
  // "(L) Conference - 4th Floor",
  // "(L) Conference - 5th Floor",
  // "(L) Conference - 6th Floor",
  // "(L) Conference - 7th Floor",
  // "(L) Conference - 8th Floor",
  // "(L) Conference - 8th Floor",
  // "(L) Open Collab - 2nd Floor",
  // "(L) Open Collab - 3rd Floor",
  // "(L) Open Collab - 4th Floor",
  // "(M) Meeting - 1R108",
  // "(M) Meeting - 2nd Floor",
  // "(M) Meeting - 3rd Floor",
  // "(M) Meeting - 4th Floor",
  // "(M) Meeting - 5th Floor",
  // "(M) Meeting - 6th Floor",
  // "(M) Meeting - 7th Floor",
  // "(M) Meeting - 8th Floor",
  // "(M) Open Collab",
  // "(M) Open Collab - 2nd Floor",
  // "(M) Open Collab - 3rd Floor",
  // "(M) Open Collab - 4th Floor",
  // "(M) Open Collab - 5th Floor",
  // "(M) Open Collab - 6th Floor",
  // "(M) Open Collab - 8th Floor",
  // "(S) Meeting",
  // "(S) Meeting - 1J250E",
  // "(S) Meeting - 2nd Floor",
  // "(S) Meeting - 3rd Floor",
  // "(S) Meeting - 4th Floor",
  // "(S) Meeting - 5th Floor",
  // "(S) Meeting - 6th Floor",
  // "(S) Meeting - 7th Floor",
  // "(S) Meeting - 8th Floor",
  // "(S) Open Collab",
  // "(S) Open Collab - 2nd Floor",
  // "(S) Open Collab - 3rd Floor",
  // "(S) Open Collab - 4th Floor",
  // "(S) Open Collab - 7th Floor",
  // "(S) Open Collab - 8th Floor",
  // "(S) Workstation - Level 5",
  // "(XL) Conference - 4th Floor",
  // "(XL) Conference - 8th Floor",
  // "(XS) Meeting - 1R106",
  // "(XS) Meeting - 2nd Floor",
  // "(XS) Meeting - 3rd Floor",
  // "(XS) Meeting - 4th Floor",
  // "(XS) Meeting - 5th Floor",
  // "(XS) Meeting - 6th Floor",
  // "(XS) Meeting - 7th Floor",
  // "1 of 3 conference rooms that can be subdivided",
  // "1 person office",
  // "1 person phone room (JIT)",
  // "1 Seat Phone",
  // "1:1 Room",
  // "1:1 Rooms",
  // "10 Pax Meeting Room",
  // "10 Pax Meeting Room",
  // "10 Person Conference Room",
  // "10 person meeting room",
  // "10 person meeting room - type 1",
  // "10 person meeting room - type 2",
  // "100- 110 SF offices",
  // "10P Conference",
  // "10p meeting",
  // "10p Meeting room",
  // "10p open meeting",
  // "10-Pax Corporate Services/GT Branch",
  // "10pax Meeting",
  // "10-Pax Meeting Room",
  // "10-Person Conference",
  // "10th Floor Workstations",
  // "11 Person",
  // "11 person conference room",
  // "110-120 Double Office",
  // "110-120 SF Offices",
  // "11-Pax Debt & CTS Office",
  // "12",
  // "12 North",
  // "12 Pax meeting Room",
  // "12 Person Conference Room",
  // "12 person meeting room",
  // "120 -130 SF  Offices",
  // "120 Degree",
  // "120 Degree Desk",
  // "120 Degree Desk 1",
  // "120 Degree Desk 2",
  // "120 degree desks",
  // "120 SF Office",
  // "120° Workstation",
  // "1200 x 800 and 1120*795 desk",
  "12-18P",
  "12'-6\" x 8'-6\" Huddle",
  "12P Conference",
  "12p meeting room",
  "12-Pax AWM DSSA",
  "Executive office on 26th Floor",
  "Executive Office Reception/Assistant",
  "Executive Office+ Admin",
  "Executive P.O.",
  "Executive Pantry",
  `Executive Soft", Conference Room`,
  "Executive Support",
  "Executive Tables",
  "Exercise Room",
  "Exercise Studio",
  // `Exercise Studio, / Activity room`,
  // "Exercise Studio with Storage",
];
