export const spaces = [
  "Conference and Collaboration",
  "Game Room (Recreation Space, Designated)",
  "Workstation",
  "Office",
  "Phone Room / Focus Room",
  "Project Room / War Room / Case Room",
  "Pantry",
  "Library / Resource Center",
  "Wellness / Mother's Room",
  "Training Room",
  "Tele-Conferencing",
  "Other",
  "Cafe",
  "Reception (Main)",
  "Auditorium",
  "Phone Room",
  "Prayer Room",
  "Gallery Space (Art, Community Display, History, etc.)",
  "Copy / Print",
  "File / Records / Archive Room",
  "Main Mail / Shipping Room",
  "Storage (Tenant Operated)",
  "Outdoor Space (Tenant Operated)",
  "Lab",
  "Fitness Room",
  "Locker Room",
  "Product Development Space",
  "Building and Grounds Storage (Tenant Operated)",
  "Staffed Food Services",
  "Retail and Services",
  "Bike Storage Room",
  "Main Copy / Print",
  "Daycare/Childcare",
  "Daycare/Childcare Outdoor",
  "Doctor's Office / Nurse's Office",
  "Exercise Studio",
  "Loading Dock (Tenant Operated)",
  "High Density File / Records",
  "Gymnasium",
  "Focus Room",
  "Meditation Room",
  "Stores and Services",
  "Massage Room",
];
